version: '3.3'
services:
  vault-server:
    image: hashicorp/vault:1.17.2
    container_name: vault-server
    ports:
      - "8200:8200"
    restart: always
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200/
    volumes:
      - ./config.hcl:/vault/config/config.hcl
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl

